django_project_B3/urls.py
# yourprojectname/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library_app.urls')),
]

library_app/urls.py
# yourappname/urls.py
from django.urls import path
from .views import home, login_user, register, logout, add_book, edit_book, delete_book, borrow_book, user_dashboard, release_book

urlpatterns = [
    path('', home, name='home'),
    path('login/', login_user, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('add_book/', add_book, name='add_book'),
    path('edit_book/<int:book_id>/', edit_book, name='edit_book'),
    path('delete_book/<int:book_id>/', delete_book, name='delete_book'),
    path('borrow_book/<int:book_id>/', borrow_book, name='borrow_book'),
    path('dashboard/', user_dashboard, name='user_dashboard'),
    path('release_book/<int:book_id>/', release_book, name='release_book'),

]

library_app/models.py
# yourappname/models.py
from django.db import models
from django.contrib.auth.models import User

class Book(models.Model):
    author = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    abstract = models.TextField()
    publication_date = models.TextField()
    image_url = models.URLField()
    borrower = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Add additional fields for user profile if needed

library_app/forms.py
# yourappname/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['author', 'title', 'abstract', 'publication_date', 'image_url']

library_app/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import user_passes_test
from .forms import BookForm
from django.http import JsonResponse
from .models import Book
import requests

@login_required
def user_dashboard(request):
    user_borrowed_books = Book.objects.filter(borrower=request.user)
    return render(request, 'user_dashboard.html', {'user_borrowed_books': user_borrowed_books})

@login_required
def release_book(request, book_id):
    book = get_object_or_404(Book, id=book_id, borrower=request.user)
    book.borrower = None
    book.save()
    return redirect('user_dashboard')

def borrow_book(request, book_id):
    if request.user.is_authenticated:
        book = get_object_or_404(Book, id=book_id, borrower=None)
        book.borrower = request.user
        book.save()
        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False, 'message': 'User not authenticated'}, status=401)

def is_superuser(user):
    return user.is_superuser

@user_passes_test(is_superuser)
def add_book(request):
    if request.method == 'POST':
        author = request.POST.get('author')
        title = request.POST.get('title')
        abstract = request.POST.get('abstract')
        publication_date = request.POST.get('publication_date')
        image_url = request.POST.get('image_url')

        Book.objects.create(
            author=author,
            title=title,
            abstract=abstract,
            publication_date=publication_date,
            image_url=image_url
        )

        return redirect('home')

    return render(request, 'add_book.html')

@user_passes_test(is_superuser)
def edit_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)

    if request.method == 'POST':
        # Update the book fields based on the form data
        book.author = request.POST.get('author')
        book.title = request.POST.get('title')
        book.abstract = request.POST.get('abstract')
        book.publication_date = request.POST.get('publication_date')
        book.image_url = request.POST.get('image_url')

        # Save the updated book
        book.save()

        return redirect('home')
    else:
        return render(request, 'edit_book.html', {'book': book})

@user_passes_test(is_superuser)
def delete_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)

    if request.method == 'POST':
        book.delete()
        return redirect('home')

    return render(request, 'delete_book.html', {'book': book})

def home(request):
    books = Book.objects.all()
    return render(request, 'home.html', {'books': books})

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('home')  # Redirect to the main page after successful login
    else:
        form = AuthenticationForm()

    return render(request, 'login.html', {'form': form})

def logout(request):
    auth_logout(request)
    return redirect('home')  # Redirect to the main page after logout

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login_user(request, user)  # Log the user in after registration
            return redirect('login')  # Redirect to the login page
    else:
        form = UserCreationForm()

    return render(request, 'register.html', {'form': form})

library_app/templates/add_book.html
{% extends 'base.html' %}

{% block title %}Add Book{% endblock %}

{% block content %}
    <div class="form-page-container">
        <div class="form-container" id="addbook-form">
            <h1 class="form-title">Ajouter un livre</h1>
            <form method="post" action="{% url 'add_book' %}" class="your-form-class">
                {% csrf_token %}

                <div class="input-container">
                    <label for="id_author">Author:</label>
                    <input type="text" name="author" required>
                </div>

                <div class="input-container">
                    <label for="id_title">Title:</label>
                    <input type="text" name="title" required>
                </div>

                <div class="input-container">
                    <label for="id_abstract">Abstract:</label>
                    <textarea name="abstract" rows="4" required></textarea>
                </div>

                <div class="input-container">
                    <label for="id_publication_date">Publication Date:</label>
                    <input type="date" name="publication_date" required>
                </div>

                <div class="input-container">
                    <label for="id_image_url">Image URL:</label>
                    <input type="url" name="image_url" required>
                </div>

                <input type="submit" value="Add Book" class="btn">
            </form>
        </div>
    </div>
{% endblock %}

library_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Your Site{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'library_app/styles.css' %}">

    </head>
<body>
    <nav>
        <p class="nav-title">The Open Source Library</p>
        <div class="links-container">

            {% if user.is_authenticated and user.is_superuser %}
                <a  class="link" href="{% url 'add_book' %}">Add Book</a>
            {% endif %}

            {% if user.is_authenticated %}
                <a class="link" href="{% url 'user_dashboard' %}">Dashboard</a>
            {% endif %}

            <a class="link" href="{% url 'home' %}">Home</a>


            {% if user.is_authenticated %}
                <a class="link nav-btn" href="{% url 'logout' %}">Se deconnecter</a></li>
            {% else %}
                <a class="link nav-btn" href="{% url 'login' %}">Connexion</a>
            {% endif %}
            
        </div>
    </nav>

    <div class="page-container">
        {% block content %}{% endblock %}
    </div>

    <footer>
        <!-- Add your footer content here -->
        <p>&copy; 2023 The Open Source Library. All rights not reserved.</p>
    </footer>

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
</body>

</html>

library_app/templates/edit_book.html
{% extends 'base.html' %}

{% block title %}Edit Book{% endblock %}

{% block content %}
    <div class="form-page-container">
        <div class="form-container" id="register-form">

            <h1 class="form-title">Edit Book</h1>
            <form method="post" action="{% url 'edit_book' book.id %}" class="your-form-class">
                {% csrf_token %}

                <div class="input-container">
                    <label for="author">Author:</label>
                    <input type="text" name="author" value="{{ book.author }}" required>
                </div>

                <div class="input-container">
                    <label for="title">Title:</label>
                    <input type="text" name="title" value="{{ book.title }}" required>
                </div>

                <div class="input-container">
                    <label for="abstract">Abstract:</label>
                    <textarea name="abstract" rows="4" required>{{ book.abstract }}</textarea>
                </div>

                <div class="input-container">
                    <label for="publication_date">Publication Date:</label>
                    <input type="date" name="publication_date" value="{{ book.publication_date }}" required>
                </div>

                <div class="input-container">
                    <label for="image_url">Image URL:</label>
                    <input type="url" name="image_url" value="{{ book.image_url }}" required>
                </div>

                <input type="submit" value="Save Changes" class="btn">
            </form>
        </div>

    </div>


{% endblock %}

library_app/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Home{% endblock %}

{% block content %}
    <h1 class="home-title">Welcome to The Open Source Library</h1>

    <div class="header-container">

        <img src="{% static 'library_app/header.svg' %}" alt="header" class="header-image">

        <div class="text-container">
            <h3>Unlock the Power of Knowledge, Embrace Freedom </h3>
            <p>At The Open Source Library, we believe that access to knowledge should be a fundamental right, unrestricted by barriers. Our mission is to foster a community where learning knows no bounds. Explore a vast collection of PDF books across genres, all available for free, because knowledge is meant to be shared.</p>
            <h3>Embracing Open Source for a Free Mind Society</h3>
            <p>In a world driven by information, open source principles pave the way for a society that thrives on the free exchange of ideas. The Open Source Library celebrates the spirit of openness, encouraging a collective pursuit of enlightenment. Here, every book is a gateway to new horizons, and every download contributes to a culture of shared wisdom.</p>
            <p>Join us on a journey where knowledge knows no bounds. Let The Open Source Library be your gateway to a world of limitless learning. Start exploring, start sharing, and together, let's build a future where information is free for all.</p>
            <a class="btn" id="header-btn" href="{% url 'register' %}">Sign Up (for free)</a>    
        </div>
    </div>
    
    <h2 class="section-title">Our Catalog</h2>

    <div class="catalog">
        {% if books %}
                    {% for book in books %}
                        <div class="book-container">

                            <div class="book-cover">
                                {% if book.image_url %}
                                    <img class="book-image" src="{{ book.image_url }}" alt="{{ book.title }} Image">
                                {% endif %}    
                            </div>

                            <div class="book-info">
                                <p class="title">{{ book.title }}</p>
                                <p class="author"><strong>Author: </strong>{{ book.author }}</p>
                                <p class="publication-date"><strong>Publication Date: </strong>{{ book.publication_date }}</p>
                                <div class="abstract">
                                    <strong>Abstract: </strong>
                                    <span class="short-abstract">{{ book.abstract|slice:":150" }}</span>
                                    {% if book.abstract|length > 150 %}
                                        <button class="see-more-btn">See More...</button>
                                    {% endif %}
                                    <span class="full-abstract" style="display: none;">{{ book.abstract }}</span>
                                </div>
                            </div>

                            {% if book.borrower %}
                                <p class="availability">Not Available</p>
                            {% else %}
                                {% if user.is_authenticated and not user.is_superuser %}
                                    <button class="borrow-btn" data-book-id="{{ book.id }}">Borrow</button>
                                {% endif %}
                            {% endif %}
                            

                            {% if user.is_authenticated and user.is_superuser %}
                            <div class="superuser-actions">
                                <a class="book-action-btn" href="{% url 'edit_book' book.id %}">Edit</a>
                                <a class="book-action-btn" href="{% url 'delete_book' book.id %}">Delete</a>
                            </div>
                            {% endif %}
                            
                        </div>

                    {% endfor %}

        {% else %}
            <p>No books available.</p>
        {% endif %}

    </div>

    <!-- Modal for book details -->
    <div id="myModal" class="modal-container">
        <div class="modal-bg-layer"></div>
        
        <div class="modal-content">
            <span class="close-btn">&times;</span>
            
            <img class="modal-image" alt="Book Image">

            <div class="modal-book-info">
                <h2 class="modal-title"></h2>
                <p class="modal-author"></p>
                <p class="full-abstract-text"></p>
            </div>
        </div>
    </div>

    <!-- Modal for borrow success -->
    <div id="borrowSuccessModal" class="modal-container">
        <div class="modal-bg-layer"></div>

        <div class="modal-content success-modal">
            <span id="closeSuccessModal" class="close-btn">&times;</span>
            <p>You just borrowed the following book: <span id="successBookName"></span></p>
        </div>
    </div>

    
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var seeMoreButtons = document.querySelectorAll('.see-more-btn');
            var modal = document.getElementById('myModal');
            var closeModal = document.querySelector('.close-btn');
            var fullAbstractText = document.querySelector('.full-abstract-text');
            var modalTitle = document.querySelector('.modal-title');
            var modalImage = document.querySelector('.modal-image');
            var modalAuthor = document.querySelector('.modal-author');
    
            seeMoreButtons.forEach(function (button) {
                button.addEventListener('click', function () {
                    var bookContainer = button.closest('.book-container');
                    var title = bookContainer.querySelector('.title').textContent;
                    var image = bookContainer.querySelector('.book-image').src;
                    var author = bookContainer.querySelector('.author').textContent;
                    var abstractContainer = bookContainer.querySelector('.abstract');
                    var fullAbstract = abstractContainer.querySelector('.full-abstract').textContent;
    
                    modal.style.visibility = 'visible';
                    modalTitle.textContent = title;
                    modalImage.src = image;
                    modalAuthor.textContent = author;
                    fullAbstractText.textContent = fullAbstract;
                });
            });
    
            closeModal.addEventListener('click', function () {
                modal.style.visibility = 'hidden';
            });
    
            window.addEventListener('click', function (event) {
                if (event.target === modal) {
                    modal.style.visibility = 'hidden';
                }
            });
            var borrowButtons = document.querySelectorAll('.borrow-btn');
            var borrowSuccessModal = document.getElementById('borrowSuccessModal');
            var successBookName = document.getElementById('successBookName');

            borrowButtons.forEach(function (button) {
                button.addEventListener('click', function () {
                    var bookId = button.dataset.bookId;

                    // Send a request to the server to update the book's borrower field
                    fetch('/borrow_book/' + bookId + '/')
                        .then(response => {
                            if (response.ok) {
                                // Book borrowed successfully, update UI
                                button.style.display = 'none';
                                var bookContainer = button.closest('.book-container');
                                var availability = document.createElement('p');
                                availability.className = 'availability';
                                availability.textContent = 'Not Available';
                                bookContainer.appendChild(availability);

                                // Display borrow success modal
                                borrowSuccessModal.style.visibility = 'visible';
                                successBookName.textContent = bookContainer.querySelector('.title').textContent;
                            } else {
                                // Handle error
                                response.json().then(data => {
                                    console.error('Failed to borrow book:', data.message);
                                    // Optionally, display an error message to the user
                                });
                            }
                        })
                        .catch(error => {
                            console.error('Error:', error);
                        });
                });
            });

            // Close the success modal when clicking on the close button
            var closeSuccessModal = document.getElementById('closeSuccessModal');
            closeSuccessModal.addEventListener('click', function () {
                borrowSuccessModal.style.visibility = 'hidden';
            });
        });
    </script> 
    
{% endblock %}

library_app/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="form-page-container">
        <div class="form-container">
            <h1 class="form-title">Login</h1>
            <form method="post" action="{% url 'login' %}">
                {% csrf_token %}

                <div class="input-container">
                    <label for="username">Username:</label>
                    <input type="text" name="username" required>
                </div>

                <div class="input-container">
                    <label for="password">Password:</label>
                    <input type="password" name="password" required>                    
                </div>

                <input type="submit" value="Login" class="btn">
                {% if form.errors %}
                    <div class="error-container">
                        <ul>
                            {% for field, errors in form.errors.items %}
                                {% for error in errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </form>            
        </div>
    </div>

{% endblock %}

library_app/templates/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
    <div class="form-page-container">
        <div class="form-container" id="register-form">

            <h1 class="form-title">Sign Up</h1>

            <form method="post" action="{% url 'register' %}">
                {% csrf_token %}

                <div class="input-container">
                    <label for="username">Username:</label>
                    <input type="text" name="username" required>
                </div>

                <div class="input-container">
                    <label for="password1">Password:</label>
                    <input type="password" name="password1" required>                    
                </div>

                <div class="input-container">
                    <label for="password2">Confirm Password:</label>
                    <input type="password" name="password2" required>
                </div>

                <input type="submit" value="Register" class="btn">
                {% if form.errors %}
                    <div class="error-container">
                        <ul>
                            {% for field, errors in form.errors.items %}
                                {% for error in errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </form>

        </div>
    </div>

{% endblock %}

library_app/templates/user_dashboard.html
{% extends 'base.html' %}

{% block title %}User Dashboard{% endblock %}

{% block content %}
    <h1>Welcome to Your Dashboard, {{ user.username }}!</h1>

    <h2>Your Borrowed Books:</h2>
    {% if user_borrowed_books %}
        <ul>
            {% for book in user_borrowed_books %}
                <li>
                    {{ book.title }} by {{ book.author }}
                    <a href="{% url 'release_book' book.id %}">Release</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>You haven't borrowed any books yet.</p>
    {% endif %}
{% endblock %}